acceaa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from  django.conf.urls.static import static


from django.views.generic import (
    RedirectView, TemplateView)

from member import urls as member_urls
from contact import urls as contact_urls
from user import urls as user_urls
from blog import urls as blog_urls


from blog.feeds import AtomPostFeed, Rss2PostFeed

from django.contrib.sitemaps import views

from django.contrib.sitemaps.views import sitemap

from django.contrib.sitemaps.views import (
    index as site_index_view,
    sitemap as sitemap_view)

from .sitemaps import sitemaps



sitenews = [
    url(r'^atom/$',
        AtomPostFeed(),
        name='blog_atom_feed'),
    url(r'^rss/$',
        Rss2PostFeed(),
        name='blog_rss_feed'),
]

urlpatterns = [


    url(r'^about/$',
        TemplateView.as_view(
            template_name='site/about.html'),
        name='about_site'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include(blog_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='sitemap'),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        sitemap_view,
        {'sitemaps': sitemaps},
        name='sitemap-sections'),

    url(r'^sitenews/', include(sitenews)),
    url(r'^', include(member_urls)),


    url(r'^user/',
        include(
            user_urls,
            app_name='user',
            namespace='dj-auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from .views import (
    PostArchiveMonth, PostArchiveYear, PostCreate,
    PostDelete, PostDetail, PostList, PostUpdate)

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name='blog_post_list'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name='blog_post_archive_month'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        PostDetail.as_view(),
        name='blog_post_detail'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name='blog_post_delete'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
]

member/urls.py
from django.conf.urls import url
from . import views

from .feeds import AtomEventFeed, Rss2EventFeed

app_name = 'member'
urlpatterns = [

    url(r'^$', views.HomePageView.as_view(), name='home'),

    # Event and Gallery
    url(r'^gallery/$', views.GalleryList.as_view(), name='gallery-list'),
    url(r'^gallery/(?P<slug>[\w\-]+)/$', views.GalleryDetailView.as_view(), name='gallery-detail'),
    url(r'^event/$', views.EventList.as_view(), name='event-list'),
    url(r'^event/gallery/$', views.EventGalleryListView.as_view(), name='event-gallery'),
    url(r'^event/create/$', views.EventCreateView.as_view(), name='member_event_create'),
    url(r'^event/(?P<slug>[\w\-]+)/$', views.EventDetailView.as_view(), name='event-detail'),
    url(r'^event/(?P<slug>[\w\-]+)/update/$', views.EventUpdateView.as_view(), name='update_event_and_gallery'),
    url(r'^event/(?P<slug>[\w\-]+)/delete/$', views.EventDelete.as_view(), name='event-delete'),

       # Executive Member
    url(r'^execomember/$', views.ExeCommListView.as_view(), name='execomember-list'),
    url(r'^execomember/create/$', views.ExeCommMembCreate.as_view(), name='execomember-create'),
    url(r'^execomember/(?P<slug>[\w\-]+)/$', views.ExeCommMembDetailView.as_view(), name='execomember-detail'),
    url(r'^execomember/(?P<slug>[\w\-]+)/update/$', views.ExeCommMembUpdate.as_view(), name='execomember-update'),
    url(r'^execomember/(?P<slug>[\w\-]+)/delete/$', views.ExeCommMembDelete.as_view(), name='execomember-delete'),

    # Member Category
    url(r'^membercat/$', views.MembershipView.as_view(), name='member-cat'),
    url(r'^membercat/create/$', views.MemberCatCreate.as_view(), name='membercat-create'),

    # Constitution
    url(r'^cons/$', views.ConstitutionView.as_view(), name='cons-list'),
    url(r'^cons/create/$', views.ConstitutionCreate.as_view(), name='cons-create'),
    url(r'^cons/(?P<slug>[\w\-]+)/update/$', views.ConstitutionUpdate.as_view(), name='cons-update'),
    url(r'^cons/(?P<slug>[\w\-]+)/delete/$', views.ConstitutionDelete.as_view(), name='cons-delete'),




    # Search

    url(r'^search/$', views.PersonSearchListView.as_view(), name='search'),

    # Tag
    url(r'^tag/$',
            views.TagList.as_view(),
        name='member_tag_list'),
    url(r'^tag/create/$',
        views.TagCreate.as_view(),
        name='member_tag_create'),
    url(r'^tag/(?P<slug>[\w\-]+)/$',
        views.TagDetail.as_view(),
        name='member_tag_detail'),
    url(r'^tag/(?P<slug>[\w-]+)/delete/$',
        views.TagDelete.as_view(),
        name='member_tag_delete'),
    url(r'^tag/(?P<slug>[\w\-]+)/update/$',
        views.TagUpdate.as_view(),
        name='member_tag_update'),

    # Member
    url(r'^person/$', views.GeneralMemberView.as_view(), name='person-list'),
    url(r'^lifemember/$', views.LifeMemberView.as_view(), name='lifemember-list'),
    url(r'^allmember/$', views.AllMemberListView.as_view(), name='all-member'),
    url(r'^person/create/$', views.PersonCreate.as_view(), name='person-create'),
    url(r'^person/(?P<slug>[\w\-]+)/$', views.PersonDetailView.as_view(), name='person-detail'),
    url(r'^(?P<person_slug>[\w\-]+)/'
        r'add_children_link/$',
        views.ChildCreate.as_view(),
        name='children-create'),
    url(r'^person/(?P<slug>[\w\-]+)/update/$', views.PersonUpdate.as_view(), name='person-update'),
    url(r'^person/(?P<slug>[\w\-]+)/delete/$', views.PersonDelete.as_view(), name='person-delete'),
    url(r'^(?P<person_slug>[\w\-]+)/'
        r'(?P<children_slug>[\w\-]+)/'
        r'delete/$',
        views.ChildDelete.as_view(),
        name='children-delete'),
    url(r'^(?P<person_slug>[\w\-]+)/'
        r'(?P<children_slug>[\w\-]+)/'
        r'update/$',
        views.ChildUpdate.as_view(),
        name='children-update'),

    # Children
    url(r'^child/$', views.ChildListView.as_view(), name='children-list'),
    url(r'^child/(?P<slug>[\w\-]+)/$', views.ChildDetailView.as_view(), name='children-detail'),

    # Event


    url(r'^(?P<event_slug>[\w-]+)/atom/$',
        AtomEventFeed(),
        name='member_event_atom_feed'),

    url(r'^(?P<event_slug>[\w-]+)/rss/$',
        Rss2EventFeed(),
        name='member_event_rss_feed'),

]

member/models.py
from django.db import models
from django.core.urlresolvers import reverse
from .file_validators import file_size, validate_file_extension
from django.conf import settings

from django.core.validators import RegexValidator

from django.utils.functional import cached_property

from django_resized import ResizedImageField
from autoslug import AutoSlugField

import datetime
from datetime import date
# Create your models here.
phone_regex = RegexValidator(regex=r'^\+(?:[0-9]●?){6,14}[0-9]$',
                                 message="Phone number format: '+999999999'. Up to 15 digits allowed.")

# r'^\+?1?\d{9,15}$'
class PersonManager(models.Manager):

    def get_by_natural_key(self, slug):
        return self.get(slug=slug)

DEGREE_CHOICES = (
    ("B.Sc(Hons)", "B.Sc(Hons)"),
    ("M.Sc", "M.Sc"),
    ("M.S", "M.S"),
    ("M.Phil", "M.Phil"),
    ("PhD", "PhD"),
        )
class Person(models.Model):
    YEAR_CHOICES = [(r, r) for r in range(1970, datetime.date.today().year + 1)]
    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='name')
    name_in_bangla = models.CharField(max_length=100)
    nick_name = models.CharField(max_length=30)
    birth_date = models.DateField()
    blood_group = models.CharField(max_length=3,validators=[RegexValidator(
                regex='^(A|B|AB|O)[+-]$',message='Blood group must be A|B|AB|O[+/-] format',),],)
    present_address = models.CharField(max_length=250, blank=True)
    permanent_address = models.CharField(max_length=250, blank=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name='member_persons')
    tele_land = models.CharField(max_length=15, validators=[phone_regex],blank=True)
    tele_cell = models.CharField(max_length=15, validators=[phone_regex], blank=True)
    photo = ResizedImageField(size=[70, 70],crop=['middle', 'center'],upload_to='persons/%Y/%m/%d/',null=True,
        blank=True,
        editable=True,
        help_text="Person Picture", validators=[file_size])

    admission_session = models.CharField(max_length=9, validators=[RegexValidator(
                regex='^(\d{4}-(\d{2}|\d{4}))$',message='Session format yyyy-yyyy not comply.',),],)
    degree_obtained = models.CharField(max_length=9,
                  choices=DEGREE_CHOICES,default="M.Sc")
    passing_year = models.IntegerField(('year'), choices=YEAR_CHOICES, default=datetime.datetime.now().year)

    # Official Informantion
    profession = models.CharField(max_length=25)
    Designation = models.CharField(max_length=40, null=True, blank=True)
    organization = models.CharField(max_length=75, blank=True)
    official_address = models.CharField(max_length=250, blank=True)
    office_phone = models.CharField(max_length=15, validators=[phone_regex], blank=True)
    office_mobile = models.CharField(max_length=15, validators=[phone_regex], blank=True)
    office_email = models.EmailField(max_length=70, null=True, blank=True)
    office_fax = models.CharField(max_length=15, validators=[phone_regex], blank=True)
    website = models.URLField(max_length=250,blank=True)

    #Bank detail

    payment_number = models.CharField(max_length=60, null=True, blank=True,)
    bank_name = models.CharField(max_length=30, null=True, blank=True,)
    branch_name = models.CharField(max_length=50, null=True, blank=True,)

    # Personal Information
    father_name = models.CharField(max_length=200)
    mother_name = models.CharField(max_length=200)
    is_married = models.BooleanField(default=True)
    national_id_no = models.IntegerField(unique=True)
    passport_no = models.CharField(max_length=15, null=True, blank=True)
    spouse_name = models.CharField(max_length=200, null=True, blank=True)
    spouse_blood_group = models.CharField(max_length=3,validators=[RegexValidator(
                regex='^(A|B|AB|O)[+-]$',message='Blood group must be A|B|AB|O[+/-] format',),],null=True, blank=True)
    category = models.ForeignKey('Membership', on_delete=models.CASCADE)

    image_height = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")
    image_width = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")
    is_active = models.BooleanField(default=True)

    objects = PersonManager()

    class Meta:
        ordering = ['name']
        unique_together = ['name', 'birth_date']

    def get_absolute_url(self):
        return reverse('member:person-detail', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('member:person-delete',
                       kwargs={'slug': self.slug})

    def get_child_create_url(self):
        return reverse(
            'member:children-create',
            kwargs={'person_slug': self.slug})

    def get_update_url(self):
        return reverse('member:person-update',
                       kwargs={'slug': self.slug})

    def __str__(self):  # __unicode__ on Python 2
        return self.name

    def natural_key(self):
        return (self.slug,)

    @property
    def photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url


class ChildManager(models.Manager):

    def get_by_natural_key(
            self, person_slug, slug):
        return self.get(
            person__slug=person_slug,
            slug=slug)

class Child(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    child_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, help_text='Slug will automaticall created from Child Name. No need to type here.')
    child_birth_date = models.DateField()
    blood_group = models.CharField(max_length=3,validators=[RegexValidator(regex='^(A|B|AB|O)[+-]$',message='Blood group must be A|B|AB|O[+/-] format',),], blank=True)

    objects = ChildManager()

    class Meta:
        verbose_name_plural = 'children'
        ordering = ['-child_birth_date']
        unique_together = ['slug', 'person']



    def __str__(self):
        return "{}: {}".format(
            self.person, self.child_name)

    def get_absolute_url(self):
        return self.person.get_absolute_url()

    def get_delete_url(self):
        return reverse(
            'member:children-delete',
            kwargs={
                'person_slug': self.person.slug,
                'children_slug': self.slug})

    def get_update_url(self):
        return reverse(
            'member:children-update',
            kwargs={
                'person_slug': self.person.slug,
                'children_slug': self.slug})


    def natural_key(self):
        return (
            self.person.natural_key(),
            self.slug)

    natural_key.dependencies = [
        'member.person']

class Membership(models.Model):
    category = models.CharField(max_length=50, blank=False, unique=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.category


class ExecMember(models.Model):
    name = models.ForeignKey(Person, on_delete=models.CASCADE ,help_text='Select Member Name')
    committee_position = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='committee_position')
    committe_period = models.CharField(max_length=9, validators=[RegexValidator(
        regex='^(\d{4}-(\d{2}|\d{4}))$', message='Period format yyyy-yyyy not comply.', ), ], )
    rank = models.IntegerField()
    member_start_date = models.DateField(blank=True)
    member_end_date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering =['-committe_period','-rank']
        unique_together = ['committe_period', 'rank']

    def get_absolute_url(self):
        return reverse('member:execomember-detail', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('member:execomember-delete',
                       kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('member:execomember-update',
                       kwargs={'slug': self.slug})

    def __str__(self):  # __unicode__ on Python 2
        return self.committee_position


class Constitution(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(populate_from='title')
    content = models.TextField()
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now_add=True)
    docfile = models.FileField(upload_to='documents/%Y/%m/%d/',null=True,
        blank=True,
        editable=True,
        help_text="Document File", validators=[file_size])


    def get_delete_url(self):
        return reverse('member:cons-delete',
                       kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('member:cons-update',
                       kwargs={'slug': self.slug})

    def __str__(self):  # __unicode__ on Python 2
        return self.title





# Tags
class TagManager(models.Manager):

    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class Tag(models.Model):
    name = models.CharField(
        max_length=31, unique=True)
    slug = AutoSlugField(populate_from='name')

    objects = TagManager()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name.title()

    def get_absolute_url(self):
        return reverse('member:member_tag_detail',
                       kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('member:member_tag_delete',
                       kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('member:member_tag_update',
                       kwargs={'slug': self.slug})

    @cached_property
    def published_posts(self):
        return tuple(self.blog_posts.filter(
            pub_date__lt=date.today()))

    def natural_key(self):
        return (self.slug,)
# Event

class EventManager(models.Manager):

member/templates/member/event_detail.html
{% extends parent_template|default:"member/base_member.html" %}


{% load partial_post_list %}

{% block title %}
{{ block.super }} - {{ event.name }}
{% endblock %}

{% block page_header %}
<div role="navigation" aria-label="breadcrumbs navigation">
    <ul class="breadcrumb">
      <li><a href="{% url 'member:event-list' %}">Event</a></li>
      <li class="active">{{ object.name }}</li>
    </ul>
  {% if perms.member.change_event or perms.member.delete_event %}
    <div class="row">
        <div class="col-sm-3 pull-left">
      {% if perms.member.change_event %}

          <a class="btn btn-primary pull-right" href="{{ event.get_update_url }}"><i class="icon-edit icon-white"></i> Edit Event and Gallery</a>


      {% endif %}
            </div>
        <div class="col-sm-6 pull-right">
      {% if perms.member.delete_event %}

          <a class="btn btn-primary "
              href="{{ event.get_delete_url }}">
              <i class="icon-edit icon-white"></i> Delete Event</a>


      {% endif %}
        </div>
    </div>
  {% endif %}
</div>

{% endblock page_header %}


{% block body %}
     <div class="col-xs-12">
            <p>Event Name: {{ object.name|title }}</p>
            <p>Event Description: {{object.description }}</p>
           <h4> Event Gallery</h4>
        </div>

    <div class="container-photo">
    <div class="row">



        <div class="photo">
        {% for gallery in event.gallery_set.all %}

            <div>
                <p>
                    {% if gallery.image %}
                     <img src="{{ gallery.image.url}}" class="img-responsive" >
                {% endif %}
                </p>

            </div>
        {% endfor %}
    </div>
</div>


  <dl>
    <dt>Created on: </dt>
      <dd>{{ event.created|date:"F jS, Y" }}</dd>


    {% with tag_list=event.tags.all %}
      <dt>Tag:{{ tag_list|pluralize }}</dt>
        {% for tag in tag_list %}
          <dd><a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
          </a></dd>
        {% endfor %}
    {% endwith %}

    <dt>Feeds</dt>
      <dd>
        <a class="feed" href="{{ event.get_feed_atom_url }}">
          Atom</a></dd>
      <dd>
        <a class="feed" href="{{ event.get_feed_rss_url }}">
          RSS</a></dd>

   </dl>




    {% if event.gallery_set.all or perms.blog.view_future_post and event.blog_posts.all or event.published_posts|length > 0 or perms.member.add_gallery %}
    <div class="row col-xs-12">

      {% if event.gallery_set.all %}
        {% if perms.blog.view_future_post and event.blog_posts.all or event.published_posts|length > 0 %}
          <section class="meta offset-by-two one-third column">
        {% else %}
          <section class="meta offset-by-two two-thirds column">
        {% endif %}
            <h3>Recent Gallery</h3>

            <ul>
              {% for gallery in event.gallery_set.all|slice:":5" %}
                <li>

                    <a href="{{ gallery.get_absolute_url}}">
                    {{ gallery.title|title }}</a>

                </li>
              {% endfor %}
            </ul>
          </section>
      {% elif perms.member.add_gallery %}
        {% if perms.blog.view_future_post and event.blog_posts.all or event.published_posts|length > 0 %}
          <section class="meta offset-by-two one-third column">
        {% else %}
          <section class="meta offset-by-two two-thirds column">
        {% endif %}

          </section>
      {% endif %}



    </div> <!-- row -->
</div>
  {% endif %}








{% endblock %}

member/templates/member/form_template.html
{% for field in form %}

<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-4">{{field.label_tag}}
    </label>
    <div class="col-sm-8">{{ field }}</div>
</div>

{% endfor %}

member/templates/member/person_list.html
{% extends parent_template|default:"member/base_member.html" %}
{% load crispy_forms_tags %}

{% block body %}


    {% if perms.member.add_person %}

       <div role="navigation" aria-label="breadcrumbs navigation">
        <ul class="breadcrumb">
          <li class="active">Member</li>
        </ul>
            <div class="row">
            <div class="col-sm-3 ">
                   <a class="btn btn-primary" href="{% url 'member:all-member' %}">View All Member</a>

            </div>

            <a class="btn btn-primary" href="{% url 'member:person-create' %}"><i class="icon-plus icon-white"></i> Add New Member</a>

            </div>
        </div>
    {% endif %}

    <div class="container-fluid">
        <div class="row ">

        <div style="overflow-x:auto;">

        <div class="col-sm-12">
            <h3>Members List</h3>

        {% if persons %}
    <table class="members">
        <thead>
            <tr>
                <th class="row-1 row-ID">Sl.No.</th>
                <th class="row-2 row-name">Name, Birth Date & Membership</th>
                <th class="row-3 row-photo">Photo</th>
                <th class="row-4 row-period">Profession & Organisation</th>
                <th class="row-5 row-contact">Contact</th>
                <th class="row-6 row-academic">Academic</th>
            </tr>
        </thead>




            {% for person in persons %}
        <tbody>
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>{{person.name}}<br>
                {{person.birth_date}}<br>
                    {{person.category}}<br>

               <strong>{{person.is_active|yesno:"Active,Inactive"}}</strong></td>

                <td><a href="{{person.get_absolute_url}}">
                <img src="{{ person.photo_url|default_if_none:'#'}}" class="img-responsive">
                </a></td>

                <td>
                {{person.profession}}<br>
                {{person.organization}}<br>
                {{person.official_address}}
                </td>

                <td>
                    {{person.present_address}}<br>
                 {{person.tele_land}}<br>
                 {{person.tele_cell}}<br>
                 {{person.user}}
                </td>

                <td>
                    {{person.admission_session}}<br>
                 {{person.degree_obtained}}<br>
                 {{person.passing_year}}<br>

                </td>


                {% if user.pk == person.user.pk and perms.member.change_person or perms.member.delete_person %}

                    {% if perms.member.change_person %}

                    <td>
                        <a href="{% url 'member:person-update' person.slug%}">
                    <button type="button" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-pencil">Update</span>
                    </button></a>
                    </td>
                    {% endif %}

                     {% if perms.member.delete_person %}

                    <td><a href="{% url 'member:person-delete' person.slug%}">
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash">Delete</span>
                    </button>
                    </a></td>
                    {% endif %}
                {% endif %}
            </tr>
        </tbody>
            {% endfor %}
            </table>
        {% else %}
            <p>No person in the list.</p>
        {% endif %}
        </div>
            </div>
    </div>
    </div>
{% endblock %}

member/templates/member/tag_detail.html
{% extends parent_template|default:"member/base_member.html" %}
{% load partial_post_list %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}


{% block page_header %}
<div role="navigation" aria-label="breadcrumbs navigation">
    <ul class="breadcrumb">
      <li><a href="{% url 'member:member_tag_list' %}">Tag</a></li>
      <li class="active">{{ object.name }}</li>
    </ul>
  {% if perms.member.change_tag or perms.member.delete_tag %}
    <div class="row">
        <div class="col-sm-3 pull-left">
      {% if perms.member.change_tag %}

          <a class="btn btn-primary pull-right" href="{{ tag.get_update_url }}"><i class="icon-edit icon-white"></i> Edit Current Tag</a>


      {% endif %}
            </div>
        <div class="col-sm-6 pull-right">
      {% if perms.member.delete_tag %}

          <a class="btn btn-primary "
              href="{{ tag.get_delete_url }}">
              <i class="icon-edit icon-white"></i> Delete Current Tag</a>


      {% endif %}
        </div>
    </div>
  {% endif %}
</div>

{% endblock page_header %}

{% block org_content %}
  <h2>{{ tag.name|title }}</h2>

  {% if tag.event_set.all %}
    <section>
      <h3>Event{{ tag.event_set.count|pluralize }}</h3>
      <p>
        Tag is associated with
        {{ tag.event_set.count }}
        event{{ tag.event_set.count|pluralize }}.
      </p>
      <ul>
        {% for event in tag.event_set.all %}
          <li><a href="{{ event.get_absolute_url }}">
            {{ event.name }}
          </a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}



  {% format_post_list tag opposite=tag.post_set.all perm_button=perms.blog.add_post %}


  {% if not perms.blog.view_future_post or not tag.blog_posts.all %}
    {% if not tag.published_posts|length > 0 %}
      {% if not tag.event_set.all %}
        <p>This tag is not related to any content.</p>
      {% endif %}
    {% endif %}
  {% endif %}


{% endblock %}

member/templates/member/tag_list.html
{% extends parent_template|default:"member/base_member.html" %}


{% block title %}
{{ block.super }} - Tag List
{% endblock %}

{% block page_header %}
<div role="navigation" aria-label="breadcrumbs navigation">
    <ol class="breadcrumb">
      <li class="active">Tag</li>
    </ol>

  {% if perms.member.add_tag %}
    <div class="col-sm-6 pull-right">
    <a class="btn btn-primary"
        href="{% url 'member:member_tag_create' %}"><i class="icon-plus icon-white"></i>

        Create New Tag</a>
  </div>

  {% endif %}
  <h3>Tag List</h3>
</div>

{% endblock page_header %}

{% block org_content %}

<div class="container">
    <div class="row">
        <div class="col-sm-6">

<div style="overflow-x:auto;">
<table class="table table-striped">

  <tr>
        <th>Tag</th>
    </tr>


    {% for tag in tag_list %}
      <tr>
        <td><a href="{{ tag.get_absolute_url }}">
          {{ tag.name|title }}</a></td>
        {% if perms.member.change_tag or perms.member.delete_tag %}

          {% if perms.member.change_tag %}
            <td>
              <a
                  href="{{ tag.get_update_url }}">
                  <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-pencil">Edit</span>
            </button></a></td>
          {% endif %}
          {% if perms.member.delete_tag %}
            <td>
              <a
                  href="{{ tag.get_delete_url }}">
                 <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash">Delete</span>
            </button></a></td>
          {% endif %}

        {% endif %}
      </tr>
    {% empty %}
      <em>There are currently no Tags available.</em>
    {% endfor %}

  </table>
</div>
    </div>
        </div>
</div>
<div><br><br></div>


{% endblock %}